"""Add goals, features and date_completed fields

Revision ID: 5a5cfc9c8de5
Revises: 
Create Date: 2026-02-03 20:59:33.157640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a5cfc9c8de5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience_description')
    with op.batch_alter_table('dev_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_completed', sa.DateTime(), nullable=True))
        batch_op.alter_column('cancel_reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('health_alcohol_logs', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('mood_diaries', schema=None) as batch_op:
        batch_op.alter_column('log_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('project_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('project_contents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'thinking_projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_contents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('project_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('mood_diaries', schema=None) as batch_op:
        batch_op.alter_column('log_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('health_alcohol_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('dev_tasks', schema=None) as batch_op:
        batch_op.alter_column('cancel_reason',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('date_completed')

    op.create_table('experience_description',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('version_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], name=op.f('experience_description_experience_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('experience_description_pkey'))
    )
    # ### end Alembic commands ###
