"""add answer and resolution fields to task_log

Revision ID: 78cce82929a5
Revises: 7d83ef6999a3
Create Date: 2026-03-28 14:42:03.793395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78cce82929a5'
down_revision = '7d83ef6999a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('old_expenses')
    with op.batch_alter_table('goal_monthly_plans', schema=None) as batch_op:
        batch_op.alter_column('monthly_push',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('saving_goals', schema=None) as batch_op:
        batch_op.alter_column('target_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responses', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_resolved', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('temp_old_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_old_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('task_logs', schema=None) as batch_op:
        batch_op.drop_column('date_resolved')
        batch_op.drop_column('is_resolved')
        batch_op.drop_column('responses')

    with op.batch_alter_table('saving_goals', schema=None) as batch_op:
        batch_op.alter_column('target_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('goal_monthly_plans', schema=None) as batch_op:
        batch_op.alter_column('monthly_push',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    op.create_table('old_expenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('expense_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('expenses_pkey'))
    )
    # ### end Alembic commands ###
