"""add goals and features to project

Revision ID: 7d83ef6999a3
Revises: 5a5cfc9c8de5
Create Date: 2026-02-07 10:31:33.817609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d83ef6999a3'
down_revision = '5a5cfc9c8de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinking_projects', schema=None) as batch_op:
        batch_op.alter_column('ref_tag',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thinking_projects', schema=None) as batch_op:
        batch_op.alter_column('ref_tag',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
