"""add task_type to dev_tasks

Revision ID: e66903822531
Revises: 78cce82929a5
Create Date: 2026-03-28 15:12:30.589816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66903822531'
down_revision = '78cce82929a5'
branch_labels = None
depends_on = None


def upgrade():
    # 1. 先新增欄位，但允許 NULL
    op.add_column('dev_tasks', sa.Column('task_type', sa.String(length=20), nullable=True))
    
    # 2. 將現有的資料更新為預設值 'feature'
    op.execute("UPDATE dev_tasks SET task_type = 'feature' WHERE task_type IS NULL")
    
    # 3. 現在資料都填滿了，可以安全地改為 NOT NULL
    op.alter_column('dev_tasks', 'task_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_tasks', schema=None) as batch_op:
        batch_op.drop_column('task_type')

    # ### end Alembic commands ###
